# Generated by Django 4.2.7 on 2023-12-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemonList',
            new_name='Demon',
        ),
    ]
