# Generated by Django 5.0 on 2023-12-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0002_rename_demonlist_demon'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='photo',
            field=models.ImageField(default=1, upload_to='demons/photos'),
            preserve_default=False,
        ),
    ]
