# Generated by Django 5.0 on 2023-12-23 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0003_demon_photo'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('video', models.CharField(max_length=500)),
                ('raw_footage', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('datetime_submit', models.DateTimeField(auto_now_add=True)),
                ('datetime_accepted', models.DateTimeField(auto_now=True)),
                ('demon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.demon')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
