# Generated by Django 5.0 on 2023-12-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0006_demon_verification_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='min_percentage',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
