# Generated by Django 5.0 on 2023-12-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0007_demon_min_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='demonlist_score',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
