# Generated by Django 5.0 on 2023-12-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0008_demon_demonlist_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='demonlist_score',
            new_name='score_complete',
        ),
    ]
