# Generated by Django 5.0 on 2023-12-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0009_rename_demonlist_score_demon_score_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='score_min',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
