# Generated by Django 4.2.7 on 2023-12-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0010_demon_score_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mod_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
