# Generated by Django 4.2.7 on 2023-12-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_list_points'),
        ('demonlist', '0011_record_mod_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod', to='users.profile'),
        ),
    ]
