# Generated by Django 4.2.7 on 2023-12-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0014_remove_record_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='score_complete',
            new_name='list_points',
        ),
    ]
