# Generated by Django 4.2.7 on 2023-12-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0015_rename_score_complete_demon_list_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='demon_difficulty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='level_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='level_password',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='object_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='update_created',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
