# Generated by Django 4.2.7 on 2023-12-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0016_demon_demon_difficulty_demon_level_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='demon_difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
