# Generated by Django 4.2.7 on 2023-12-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0017_alter_demon_demon_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('position', models.IntegerField()),
                ('change_number', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, choices=[('Up', 'Up'), ('Down', 'Down')], max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('demon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.demon')),
            ],
        ),
    ]
