# Generated by Django 4.2.7 on 2023-12-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0020_alter_changelog_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.TimeField(default='01:00:00'),
            preserve_default=False,
        ),
    ]
