# Generated by Django 4.2.7 on 2023-12-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0021_record_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time',
            new_name='best_time',
        ),
    ]
