# Generated by Django 4.2.7 on 2023-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0022_rename_time_record_best_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='list_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
