# Generated by Django 5.0 on 2023-12-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0023_alter_demon_list_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='list_points',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
