# Generated by Django 4.2.7 on 2023-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0024_alter_demon_list_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('changes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
