# Generated by Django 4.2.7 on 2023-12-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0025_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='verification_video',
            new_name='verification_video_embed',
        ),
    ]
