# Generated by Django 4.2.7 on 2023-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0026_rename_verification_video_demon_verification_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='verification_video',
            field=models.CharField(default='y', max_length=500),
            preserve_default=False,
        ),
    ]
