# Generated by Django 4.2.7 on 2023-12-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0027_demon_verification_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='raw_footage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
