# Generated by Django 4.2.7 on 2023-12-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0028_alter_record_raw_footage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
