# Generated by Django 4.2.7 on 2023-12-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0029_alter_record_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='list_points',
            field=models.FloatField(default=0),
        ),
    ]
