# Generated by Django 4.2.7 on 2023-12-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0030_alter_demon_list_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='top_best_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
