# Generated by Django 4.2.7 on 2024-01-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0031_record_top_best_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='top_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
