# Generated by Django 4.2.7 on 2024-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0034_alter_demon_verification_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='verification_video_embed',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
