# Generated by Django 4.2.7 on 2024-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0035_alter_demon_verification_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='all_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='atmosphere_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='balanced_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='decoration_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='enjoyment_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='gameplay_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='atmosphere_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='balanced_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='decoration_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='enjoyment_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='gameplay_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
