# Generated by Django 4.2.7 on 2024-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0036_demon_all_stars_demon_atmosphere_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='all_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='atmosphere_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='balanced_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='decoration_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='enjoyment_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='gameplay_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='atmosphere_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='balanced_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='decoration_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='enjoyment_stars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='gameplay_stars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
