# Generated by Django 4.2.7 on 2024-01-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_ranking'),
        ('demonlist', '0037_alter_demon_all_stars_alter_demon_atmosphere_stars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('max_demons', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouletteDemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demon_index', models.PositiveIntegerField()),
                ('demon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.demon')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonlist.roulette')),
            ],
            options={
                'ordering': ['demon_index'],
            },
        ),
        migrations.AddField(
            model_name='roulette',
            name='demons',
            field=models.ManyToManyField(blank=True, through='demonlist.RouletteDemon', to='demonlist.demon'),
        ),
        migrations.AddField(
            model_name='roulette',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
