# Generated by Django 4.2.7 on 2024-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0039_demon_level_id_ldm'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettedemon',
            name='num_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roulettedemon',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
