# Generated by Django 4.2.7 on 2024-01-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0040_roulettedemon_num_level_roulettedemon_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettedemon',
            name='num_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roulettedemon',
            name='stage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
