# Generated by Django 4.2.7 on 2024-01-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0041_alter_roulettedemon_num_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
