# Generated by Django 4.2.7 on 2024-01-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_ranking'),
        ('demonlist', '0042_roulette_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='players_to_share',
            field=models.ManyToManyField(null=True, related_name='players_to_share', to='users.profile'),
        ),
    ]
