# Generated by Django 4.2.7 on 2024-01-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_ranking'),
        ('demonlist', '0043_roulette_players_to_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='players_to_share',
            field=models.ManyToManyField(blank=True, null=True, related_name='players_to_share', to='users.profile'),
        ),
    ]
