# Generated by Django 4.2.7 on 2024-01-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0044_alter_roulette_players_to_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='reason_demon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason_demon', to='demonlist.demon'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='demon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demon', to='demonlist.demon'),
        ),
    ]
