# Generated by Django 4.2.7 on 2024-01-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0045_changelog_reason_demon_changelog_reason_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='all_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='atmosphere_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='balanced_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='decoration_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='enjoyment_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='gameplay_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
