# Generated by Django 4.2.7 on 2024-01-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0046_alter_demon_all_stars_alter_demon_atmosphere_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='category',
            field=models.CharField(choices=[('rated', 'rated'), ('unrated', 'unrated')], default='rated', max_length=100),
        ),
    ]
