# Generated by Django 4.2.7 on 2024-01-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0047_demon_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='position',
            new_name='rated_position',
        ),
    ]
