# Generated by Django 4.2.7 on 2024-01-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0048_rename_position_demon_rated_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='all_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='un_rated_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='rated_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
