# Generated by Django 4.2.7 on 2024-01-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0051_rename_un_rated_position_changelog_unrated_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='un_rated_position',
            new_name='unrated_position',
        ),
    ]
