# Generated by Django 4.2.7 on 2024-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0052_rename_un_rated_position_demon_unrated_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='rated_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated')], max_length=500, null=True),
        ),
    ]
