# Generated by Django 4.2.7 on 2024-02-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0053_alter_changelog_rated_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
