# Generated by Django 4.2.7 on 2024-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0056_demon_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='creator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='verificator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
