# Generated by Django 4.2.7 on 2024-02-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0057_alter_demon_creator_alter_demon_verificator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='verification_video',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
