# Generated by Django 4.2.7 on 2024-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0058_alter_demon_verification_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='challenge_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge')], default='rated', max_length=100),
        ),
    ]
