# Generated by Django 4.2.7 on 2024-02-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0060_changelog_challenge_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge')], max_length=500, null=True),
        ),
    ]
