# Generated by Django 4.2.7 on 2024-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0065_demon_min_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='best_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
