# Generated by Django 4.2.7 on 2024-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0066_record_percentage_alter_record_best_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='mode',
            field=models.CharField(choices=[('classic', 'classic'), ('platformer', 'platformer')], default='platformer', max_length=100),
        ),
    ]
