# Generated by Django 4.2.7 on 2024-02-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0067_roulette_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='min_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
