# Generated by Django 4.2.7 on 2024-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0068_roulette_min_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roulette',
            name='min_percentage',
        ),
        migrations.AddField(
            model_name='roulettedemon',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
