# Generated by Django 4.2.7 on 2024-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0069_remove_roulette_min_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulettedemon',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
