# Generated by Django 4.2.7 on 2024-03-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0070_alter_roulettedemon_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='datetime_accepted',
            new_name='datetime_checked',
        ),
    ]
