# Generated by Django 4.2.7 on 2024-04-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0071_rename_datetime_accepted_record_datetime_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='removed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('removed', 'removed')], max_length=500, null=True),
        ),
    ]
