# Generated by Django 4.2.7 on 2024-04-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0073_alter_demon_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettedemon',
            name='best_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
