# Generated by Django 4.2.5 on 2024-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0074_roulettedemon_best_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roulette',
            name='mode',
            field=models.CharField(choices=[('classic', 'classic'), ('platformer', 'platformer'), ('platformer_best_time', 'platformer_best_time')], default='platformer', max_length=100),
        ),
    ]
