# Generated by Django 4.2.5 on 2024-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0076_roulette_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tentative_player',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
