# Generated by Django 4.2.5 on 2024-04-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_profile_claimable'),
        ('demonlist', '0077_record_tentative_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
