# Generated by Django 4.2.5 on 2024-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0078_alter_record_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='all_demonlist',
            field=models.BooleanField(default=False),
        ),
    ]
