# Generated by Django 4.2.5 on 2024-04-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0080_demon_downloaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='downloaded',
            new_name='downloads',
        ),
    ]
