# Generated by Django 4.2.5 on 2024-04-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0081_rename_downloaded_demon_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='likes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
