# Generated by Django 4.2.5 on 2024-04-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0082_demon_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='type',
            field=models.CharField(blank=True, choices=[('featured', 'featured'), ('epic', 'epic'), ('legendary', 'legendary'), ('mythic', 'mythic')], max_length=100, null=True),
        ),
    ]
