# Generated by Django 4.2.5 on 2024-04-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0083_demon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='length',
            field=models.CharField(blank=True, choices=[('tiny', 'tiny'), ('short', 'short'), ('medium', 'medium'), ('long', 'long'), ('xl', 'xl'), ('platformer', 'platformer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='type',
            field=models.CharField(blank=True, choices=[('featured', 'featured'), ('epic', 'epic'), ('legendary', 'legendary'), ('mythic', 'mythic')], max_length=100, null=True),
        ),
    ]
