# Generated by Django 4.2.5 on 2024-04-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0084_demon_length_alter_demon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='artist_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='number_of_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='song_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='song_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='song_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='song_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='two_players',
            field=models.BooleanField(default=False),
        ),
    ]
