# Generated by Django 4.2.5 on 2024-04-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0087_roulette_demon_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='extreme_filter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
