# Generated by Django 4.2.5 on 2024-04-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0088_roulette_extreme_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roulettedemon',
            options={},
        ),
    ]
