# Generated by Django 4.2.5 on 2024-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0090_record_under_consideration'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='easiest_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
