# Generated by Django 4.2.5 on 2024-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0092_changelog_easiest_position_alter_demon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='shitty_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='shitty_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
