# Generated by Django 4.2.5 on 2024-04-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0094_alter_demon_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demon',
            old_name='verificator',
            new_name='verifier',
        ),
    ]
