# Generated by Django 4.2.5 on 2024-04-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_alter_profile_device'),
        ('demonlist', '0095_rename_verificator_demon_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='creator_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='demon',
            name='verifier_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier_profile', to='users.profile'),
        ),
    ]
