# Generated by Django 4.2.5 on 2024-04-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0097_roulette_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('shitty', 'shitty'), ('removed', 'removed')], max_length=500, null=True),
        ),
    ]
