# Generated by Django 4.2.5 on 2024-05-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0099_demon_verification_record_demon_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='future_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
