# Generated by Django 4.2.7 on 2024-05-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0101_changelog_future_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDemon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('demonlist.demon',),
        ),
    ]
