# Generated by Django 4.2.7 on 2024-06-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_profile_language'),
        ('demonlist', '0102_listdemon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListDemon',
        ),
        migrations.CreateModel(
            name='ExtendedDemon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('demonlist.demon',),
        ),
        migrations.CreateModel(
            name='ExtendedRecord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('demonlist.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='users.profile'),
        ),
    ]
