# Generated by Django 4.2.7 on 2024-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0103_delete_listdemon_extendeddemon_extendedrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mods',
            field=models.CharField(blank=True, choices=[('click_between_frames', 'click_between_frames')], max_length=200, null=True),
        ),
    ]
