# Generated by Django 4.2.7 on 2024-07-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0104_record_mods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='mods',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
