# Generated by Django 4.2.7 on 2024-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0105_alter_record_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='tiny_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny')], default='rated', max_length=100),
        ),
    ]
