# Generated by Django 4.2.7 on 2024-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0106_demon_tiny_position_alter_demon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='tiny_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('shitty', 'shitty'), ('tiny', 'tiny'), ('removed', 'removed')], max_length=500, null=True),
        ),
    ]
