# Generated by Django 4.2.7 on 2024-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0107_changelog_tiny_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='deathless_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='deathless_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='reason_option',
            field=models.CharField(blank=True, choices=[('added_to_list', 'added_to_list'), ('added_above', 'added_above'), ('moved_up', 'moved_up'), ('moved_down', 'moved_down'), ('moved', 'moved'), ('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('shitty', 'shitty'), ('tiny', 'tiny'), ('deathless', 'deathless'), ('removed', 'removed')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny'), ('deathless', 'deathless')], default='rated', max_length=100),
        ),
    ]
