# Generated by Django 4.2.7 on 2024-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0108_changelog_deathless_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='deathless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny')], default='rated', max_length=100),
        ),
    ]
