# Generated by Django 4.2.7 on 2024-08-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0109_demon_deathless_alter_demon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='deathless_list_points',
            field=models.FloatField(default=0),
        ),
    ]
