# Generated by Django 4.2.7 on 2024-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0110_demon_deathless_list_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(blank=True, choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny')], default='rated', max_length=100, null=True),
        ),
    ]
