# Generated by Django 4.2.7 on 2024-08-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0111_alter_demon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deathless',
            field=models.BooleanField(default=False),
        ),
    ]
