# Generated by Django 4.2.7 on 2024-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0112_record_deathless'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='impossible_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(blank=True, choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny'), ('impossible', 'impossible')], default='rated', max_length=100, null=True),
        ),
    ]
