# Generated by Django 4.2.7 on 2024-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0114_changelog_impossible_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='impossible_list_points',
            field=models.FloatField(default=0),
        ),
    ]
