# Generated by Django 4.2.7 on 2024-09-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0115_demon_impossible_list_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('platformer', 'platformer')], default='platformer', max_length=100)),
                ('category', models.CharField(choices=[('rated', 'rated')], default='rated', max_length=100)),
                ('demons', models.ManyToManyField(related_name='level_packs', to='demonlist.demon')),
            ],
        ),
    ]
