# Generated by Django 4.2.7 on 2024-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0116_levelpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelpack',
            name='color',
            field=models.CharField(choices=[('dark_green', 'dark_green')], default='dark_green', max_length=100),
            preserve_default=False,
        ),
    ]
