# Generated by Django 4.2.7 on 2024-09-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0117_levelpack_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='spam_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(blank=True, choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny'), ('impossible', 'impossible'), ('spam', 'spam')], default='rated', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='levelpack',
            name='color',
            field=models.CharField(choices=[('beginner', 'beginner'), ('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('amber', 'amber'), ('platinum', 'platinum'), ('sapphire', 'sapphire'), ('jade', 'jade'), ('emerald', 'emerald'), ('ruby', 'ruby'), ('diamond', 'diamond'), ('onyx', 'onyx'), ('amethyst', 'amethyst'), ('azurite', 'azurite'), ('obsidian', 'obsidian')], max_length=100),
        ),
    ]
