# Generated by Django 4.2.7 on 2024-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0121_changelog_impossible_tiny_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelpack',
            name='color_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
