# Generated by Django 4.2.7 on 2024-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0122_levelpack_color_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='demon',
            name='verification_video_deathles',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='demon',
            name='verification_video_embed_deathles',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
