# Generated by Django 4.2.7 on 2024-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0125_demon_all_list_points_alter_demon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='category',
            field=models.CharField(blank=True, choices=[('rated', 'rated'), ('unrated', 'unrated'), ('challenge', 'challenge'), ('easiest', 'easiest'), ('shitty', 'shitty'), ('future', 'future'), ('tiny', 'tiny'), ('deathless', 'deathless'), ('impossible', 'impossible'), ('spam', 'spam'), ('impossible_tiny', 'impossible_tiny'), ('all', 'all')], default='rated', max_length=100, null=True),
        ),
    ]
