# Generated by Django 4.2.7 on 2024-11-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0126_alter_demon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='demons/photos'),
        ),
    ]
