# Generated by Django 4.2.7 on 2024-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonlist', '0127_alter_demon_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulette',
            name='ronda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
