# Generated by Django 4.2.7 on 2023-12-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='youtube_channel',
        ),
    ]
