# Generated by Django 4.2.7 on 2023-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_points',
            field=models.IntegerField(blank=True, default=70),
            preserve_default=False,
        ),
    ]
