# Generated by Django 5.0 on 2023-12-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_list_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': []},
        ),
    ]
