# Generated by Django 4.2.7 on 2023-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='country',
            name='list_points',
            field=models.FloatField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='list_points',
            field=models.FloatField(blank=True),
        ),
    ]
