# Generated by Django 4.2.7 on 2023-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='list_points',
            field=models.FloatField(default=0),
        ),
    ]
