# Generated by Django 4.2.7 on 2023-12-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_country_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='countries/pictures'),
        ),
    ]
