# Generated by Django 4.2.7 on 2023-12-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_country_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
