# Generated by Django 4.2.7 on 2024-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_notification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ManyToManyField(null=True, related_name='profile', to='users.profile'),
        ),
    ]
