# Generated by Django 4.2.7 on 2024-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_notification_profiles_notification_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Russian', 'Russian'), ('German', 'German')], max_length=12, null=True),
        ),
    ]
