# Generated by Django 4.2.7 on 2024-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Russian', 'Russian'), ('German', 'German')], default='English', max_length=12),
        ),
    ]
