# Generated by Django 4.2.7 on 2024-01-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_notification_parameter_alter_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_spanish',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
