# Generated by Django 4.2.7 on 2024-01-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_country_country_spanish_alter_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_spanish',
        ),
    ]
