# Generated by Django 4.2.7 on 2024-01-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_country_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
            ],
        ),
    ]
