# Generated by Django 4.2.7 on 2024-01-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_country_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_roulette_parameter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
