# Generated by Django 4.2.7 on 2024-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_notification_id_roulette_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_german',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='country_russian',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
