# Generated by Django 4.2.7 on 2024-01-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_teaminvitation_delete_teaminvitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
    ]
