# Generated by Django 4.2.7 on 2024-01-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='id_team_parameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('record_accepted', 'record_accepted'), ('record_rejected', 'record_rejected'), ('demon_beaten', 'demon_beaten'), ('roulette_shared', 'roulette_shared'), ('following', 'following'), ('team_invitation', 'team_invitation')], max_length=500),
        ),
    ]
