# Generated by Django 4.2.7 on 2024-02-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_rename_list_points_country_platformer_list_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='platformer_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='platformer_list_points',
            field=models.FloatField(default=0),
        ),
    ]
