# Generated by Django 4.2.7 on 2024-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_country_classic_list_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='record_parameter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
