# Generated by Django 4.2.7 on 2024-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_notification_record_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platformer_challenge_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_unrated_list_points',
            field=models.FloatField(default=0),
        ),
    ]
