# Generated by Django 4.2.7 on 2024-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_profile_platformer_challenge_list_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='platformer_challenge_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='platformer_unrated_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='platformer_challenge_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='platformer_unrated_list_points',
            field=models.FloatField(default=0),
        ),
    ]
