# Generated by Django 4.2.5 on 2024-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_czech',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
