# Generated by Django 4.2.5 on 2024-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_country_country_czech'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claimable',
            field=models.BooleanField(default=False),
        ),
    ]
