# Generated by Django 4.2.5 on 2024-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_profile_claimable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roulette_animation',
            field=models.BooleanField(default=True),
        ),
    ]
