# Generated by Django 4.2.5 on 2024-04-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('record_accepted', 'record_accepted'), ('record_rejected', 'record_rejected'), ('record_under_consideration', 'record_under_consideration'), ('demon_beaten', 'demon_beaten'), ('roulette_shared', 'roulette_shared'), ('following', 'following'), ('team_invitation', 'team_invitation')], max_length=500),
        ),
    ]
