# Generated by Django 4.2.5 on 2024-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device',
            field=models.CharField(blank=True, choices=[('mouse', 'mouse'), ('keyboard', 'keyboard'), ('mobile', 'mobile')], max_length=12, null=True),
        ),
    ]
