# Generated by Django 4.2.5 on 2024-04-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_alter_profile_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='classic_shitty_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_shitty_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_shitty_list_points',
            field=models.FloatField(default=0),
        ),
    ]
