# Generated by Django 4.2.5 on 2024-05-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_profile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
