# Generated by Django 4.2.7 on 2024-05-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_country_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedCountry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.country',),
        ),
        migrations.CreateModel(
            name='ExtendedProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='ExtendedTeam',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.team',),
        ),
    ]
