# Generated by Django 4.2.7 on 2024-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_extendedcountry_extendedprofile_extendedteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_turkish',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
