# Generated by Django 4.2.7 on 2024-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_country_country_danish'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_portuguese',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Russian', 'Russian'), ('German', 'German'), ('Czech', 'Czech'), ('Turkish', 'Turkish'), ('Danish', 'Danish')], default='English', max_length=12),
        ),
    ]
