# Generated by Django 4.2.7 on 2024-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_country_country_portuguese_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Russian', 'Russian'), ('German', 'German'), ('Czech', 'Czech'), ('Turkish', 'Turkish'), ('Danish', 'Danish'), ('Portuguese', 'Portuguese')], default='English', max_length=12),
        ),
    ]
