# Generated by Django 4.2.7 on 2024-07-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classic_challenge_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_shitty_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_unrated_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_challenge_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_unrated_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
    ]
