# Generated by Django 4.2.7 on 2024-07-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_profile_classic_challenge_list_points_with_mods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='platformer_challenge_list_points_with_mods',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='platformer_list_points_with_mods',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='platformer_unrated_list_points_with_mods',
        ),
        migrations.AddField(
            model_name='country',
            name='classic_challenge_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='classic_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='classic_shitty_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='classic_unrated_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_challenge_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_shitty_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_unrated_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
    ]
