# Generated by Django 4.2.7 on 2024-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_remove_profile_platformer_challenge_list_points_with_mods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_french',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
