# Generated by Django 4.2.7 on 2024-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_country_country_french'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Russian', 'Russian'), ('German', 'German'), ('Czech', 'Czech'), ('Turkish', 'Turkish'), ('Danish', 'Danish'), ('Portuguese', 'Portuguese'), ('French', 'French')], default='English', max_length=12),
        ),
    ]
