# Generated by Django 4.2.7 on 2024-07-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_alter_profile_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='classic_challenge_list_points',
            new_name='classic_tiny_list_points',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='classic_challenge_list_points_with_mods',
            new_name='classic_tiny_list_points_with_mods',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='classic_challenge_list_points',
            new_name='classic_tiny_list_points',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='classic_challenge_list_points_with_mods',
            new_name='classic_tiny_list_points_with_mods',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='classic_challenge_list_points',
            new_name='classic_tiny_list_points',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='classic_challenge_list_points_with_mods',
            new_name='classic_tiny_list_points_with_mods',
        ),
    ]
