# Generated by Django 4.2.7 on 2024-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_rename_classic_challenge_list_points_country_classic_tiny_list_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='platformer_deathless_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_deathless_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='platformer_deathless_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stats_viewer',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_submit_record',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge')], max_length=100, null=True),
        ),
    ]
