# Generated by Django 4.2.7 on 2024-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_alter_profile_default_stats_viewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
