# Generated by Django 4.2.7 on 2024-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_country_classic_spam_list_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='classic_impossible_tiny_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='classic_impossible_tiny_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_impossible_tiny_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='classic_impossible_tiny_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_impossible_tiny_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='classic_impossible_tiny_list_points_with_mods',
            field=models.FloatField(default=0),
        ),
    ]
