# Generated by Django 4.2.7 on 2024-09-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_country_classic_impossible_tiny_list_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='platformer_tiny_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_tiny_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='platformer_tiny_list_points',
            field=models.FloatField(default=0),
        ),
    ]
