# Generated by Django 4.2.7 on 2024-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_country_platformer_tiny_list_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_stats_viewer',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('classic spam', 'classic spam'), ('classic impossible_tiny', 'classic impossible_tiny'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge'), ('platformer deathless', 'platformer deathless'), ('platformer impossible', 'platformer impossible'), ('platformer tiny', 'platformer tiny')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_submit_record',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('classic spam', 'classic spam'), ('classic impossible_tiny', 'classic impossible_tiny'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge'), ('platformer deathless', 'platformer deathless'), ('platformer impossible', 'platformer impossible'), ('platformer tiny', 'platformer tiny')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('classic rated', 'classic rated'), ('classic unrated', 'classic unrated'), ('classic tiny', 'classic tiny'), ('classic shitty', 'classic shitty'), ('classic spam', 'classic spam'), ('classic impossible_tiny', 'classic impossible_tiny'), ('platformer rated', 'platformer rated'), ('platformer unrated', 'platformer unrated'), ('platformer challenge', 'platformer challenge'), ('platformer deathless', 'platformer deathless'), ('platformer impossible', 'platformer impossible'), ('platformer tiny', 'platformer tiny')], max_length=100, null=True),
        ),
    ]
