# Generated by Django 4.2.7 on 2024-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_alter_profile_default_stats_viewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='platformer_all_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='platformer_all_list_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='platformer_all_list_points',
            field=models.FloatField(default=0),
        ),
    ]
